# Generated by Django 5.2.6 on 2025-09-27 04:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='accepted_by',
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='accepted_donors',
            field=models.ManyToManyField(blank=True, related_name='donated_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
