# Generated by Django 5.2.6 on 2025-09-27 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0002_remove_bloodrequest_accepted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='requester_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='requester_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
