# Generated by Django 5.2.6 on 2025-09-28 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_camp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodcamp',
            old_name='created_by',
            new_name='organizer',
        ),
    ]
